language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t edaram/docker-react -f Dockerfile.dev

script:
    - docker run CI=true edaram/docker-react npm run test -- --coverage

