sudo: required
services: 
    - docker

before_install:
    - docker build -t edaram/docker-react -f Dockerfile.dev .

script:
    - docker run edaram/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "dockerreact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-584059357638"
    bucket_path: "dockerreact"
    on :
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: 
            secret: "$AWS_SECRET_KEY"



